### PR TITLE
[WIP][Bug] Fixes #50 - Raise an error when selecting project & update

### LINKED ISSUE #50: Nasty error message when project is not found
When running `checklister new --checklist some_valid_md_file.md`, I get prompted for a project name. If I enter something that doesn't match any projects, I get the following output:

```
error: undefined method `[]' for nil:NilClass
```

It would be nice if `checklister` could tell us nicely it didn't find any projects matching the entered string.

### PR DESCRIPTION
**Pull request by mdeloupy**
gitignore

### CODE REVIEW

**Comment by mdeloupy** [comment]
@benichu Ready for review

**Comment by benichu** [comment]
@mdeloupy do you want me to look into it?

**Comment by mdeloupy** [comment]
@benichu Désolée je suis passée à coté du mail, je m'en occupe ce soir.

**Comment by mdeloupy** [comment]
@benichu Fixed the `raise exception` issue with `while` loops. What do you think ? I guess it would need refactor, but it's already working "as is" on my end.

**Pull request merged**
