### PR TITLE
#37 - We should be able to override the issue's title we create with a CLI option

### PR DESCRIPTION
**Pull request by mdeloupy**

### CODE REVIEW

**Comment by mdeloupy** [comment]
@benichu Ready for review before squash

**Comment by benichu** [comment]
looks good... any specs coming up?

**Comment by benichu** [comment]
don't forget to update the README with an example...

**Comment by mdeloupy** [comment]
@benichu Once again, ready for review :-)

**Comment by benichu** [comment]
Ready to squash and merge

**Pull request merged**
